version: '3'

services:
  pgsql:
    image: postgres:latest
    ports:
      - '5432:5432'
    container_name: 'pgsql_nest'
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: nestjs 
